[global]
disable = [
  "MD013",  # line length
  "MD014",  # command should show output (removes '$' immediately)
  "MD026",  # heading ends with punctuation
  "MD030",  # spaces after list marker
  "MD033",  # inline HTML
  "MD034",  # URL without angle brackets
  "MD036",  # emphasis used instead of heading
  "MD040",  # code block missing language (gets fixed to "text")
  "MD041",  # first line in file should be a h1
  "MD059",  # nondescriptive link text
]
