import { useState, useEffect, useCallback, useId } from "react";
import { useQueryString } from "@docusaurus/theme-common";
import Heading from "@theme/Heading";
import Admonition from "@theme/Admonition";
import Markdown from "@site/src/components/OurMarkdown";
import prefetchedLinterMessages from "@site/static/schema/linter-messages.json";
import { urls } from "@site/src/constants";

export default function LinterMessages({ toc = null }) {
  const messagesURL = urls.linter.messages;
  const [showDeprecated, _] = useDeprecated();
  const [messages, setMessages] = useState(prefetchedLinterMessages);
  useEffect(() => {
    fetch(messagesURL, {
      headers: {
        Accept: "application/json",
      },
    })
      .then((response) => response.json())
      .then((parsed) => setMessages(parsed));
  }, []);

  // Group messages by category, considering deprecation status
  const groupedMessages = {};
  if (messages.messages) {
    for (const message of messages.messages) {
      if (!groupedMessages[message.category]) {
        groupedMessages[message.category] = [];
      }
      if (message.deprecated_in.length === 0 || showDeprecated) {
        groupedMessages[message.category].push(message);
      }
    }
  }
  // We will only publish categories with messages
  const populatedCategories = {};
  for (const category in messages.categories) {
    if (groupedMessages[category].length > 0) {
      populatedCategories[category] = messages.categories[category];
    }
  }

  return (
    <>
      <Admonition type="info">
        This documentation is autogenerated from{" "}
        <a href={messagesURL} target="_blank">
          conda-smithy's linter messages JSON document
        </a>
        .
      </Admonition>
      <ToggleDeprecated />
      <Heading as="h2" id="categories">
        Available categories
      </Heading>
      <CategoriesToc categories={populatedCategories} />
      <Heading as="h2" id="messages">
        Messages
      </Heading>
      {populatedCategories &&
        Object.entries(populatedCategories).map(([id, description]) => (
          <Category
            id={id}
            description={description}
            messages={messages}
            toc={toc}
            showDeprecated={showDeprecated}
          />
        ))}
    </>
  );
}

function Category({
  id,
  description,
  messages,
  toc = null,
  showDeprecated = false,
}) {
  if (toc) {
    toc.push({
      value: `${id}: ${description.replaceAll("`", "")}`,
      id: id,
      level: 2,
    });
  }
  return (
    <>
      <Heading as="h3" id={id} key={id}>
        {id}: {description.replaceAll("`", "")}
      </Heading>
      {messages.messages &&
        messages.messages.map(
          (message) =>
            message.category == id && (
              <Message
                message={message}
                toc={toc}
                showDeprecated={showDeprecated}
              />
            ),
        )}
    </>
  );
}

function Message({ message, toc = null, showDeprecated = false }) {
  if (toc && (message.deprecated_in === "" || showDeprecated)) {
    toc.push({ value: message.identifier, id: message.identifier, level: 3 });
  }
  return (
    <>
      <Heading as="h4" id={message.identifier} key={message.identifier}>
        {(message.deprecated_in && (
          <s>
            {message.identifier}: {message.name}
          </s>
        )) || (
            <>
              {message.identifier}: {message.name}
            </>
          )}
      </Heading>
      {(message.deprecated_in && (
        <p>
          <span className={["badge", "badge--danger"].join(" ")}>
            Deprecated in {message.deprecated_in}
          </span>
        </p>
      )) || 
        null}
      <ul key={`${message.identifier}-ul`}>
        <li key={`${message.identifier}-kind-${message.kind}`}>
          {(message.kind == "lint" && "🚨 Lint") || "ℹ️ Hint"}
        </li>
        <li key={`${message.identifier}-added-${message.added_in}`}>
          Added in conda-smithy {message.added_in}
        </li>
        {(message.path && (
          <li key={`${message.identifier}-path-${message.path}`}>
            Affected path: <code>{message.path}</code>
          </li>
        )) ||
          null}
      </ul>
      <Markdown>{message.documentation}</Markdown>
      {(message.message.length > 0 && (
        <>
          <p>
            <strong>Message or template</strong>
          </p>
          <Admonition type="info" title={null} icon={null}>
            <Markdown>{message.message}</Markdown>
          </Admonition>
        </>
      )) ||
        null}
      {message.examples.length > 0 && (
        <>
          <p>
            <strong>Examples</strong>
          </p>
          {message.examples.map((example, idx) => (
            <Admonition
              type="note"
              title={null}
              icon={null}
              key={`${message.identifier}-example-${idx}`}
            >
              <Markdown>{example}</Markdown>
            </Admonition>
          ))}
        </>
      )}
      <hr />
    </>
  );
}

function CategoriesToc({ categories }) {
  return (
    <ul>
      {categories &&
        Object.entries(categories).map(([id, desc]) => (
          <li key={`toc-${id}`}>
            <a href={`#${id}`} key={id}>
              {id}: {desc.replaceAll("`", "")}
            </a>
          </li>
        ))}
    </ul>
  );
}

function useDeprecated() {
  const [deprecatedQuery, setDeprecatedQuery] = useQueryString("deprecated");
  const deprecated = deprecatedQuery === "true";
  const toggleDeprecated = useCallback(() => {
    const newDeprecated = !deprecated;
    setDeprecatedQuery(newDeprecated);
  }, [deprecated, setDeprecatedQuery]);
  return [deprecated, toggleDeprecated];
}

function ToggleDeprecated() {
  const id = useId();
  const [deprecated, toggleDeprecated] = useDeprecated(false);
  return (
    <div className="check-box">
      <input
        id={id}
        className="toggle-switch"
        type="checkbox"
        aria-label="Show or hide deprecated rules"
        checked={deprecated}
        onChange={toggleDeprecated}
        onKeyDown={(e) => {
          if (e.key === "Enter") {
            toggleDeprecated();
          }
        }}
      />
      <label> Show deprecated rules</label>
    </div>
  );
}
