import { useState, useEffect } from "react";
import Heading from "@theme/Heading";
import Admonition from "@theme/Admonition";
import Markdown from "@site/src/components/OurMarkdown";
import prefetchedLinterMessages from "@site/static/schema/linter-messages.json";
import { urls } from "@site/src/constants";

export default function LinterMessages({ toc = null }) {
  const messagesURL = urls.linter.messages;
  const [messages, setMessages] = useState(prefetchedLinterMessages);
  useEffect(() => {
    fetch(messagesURL, {
      headers: {
        Accept: "application/json",
      },
    })
      .then((response) => response.json())
      .then((parsed) => setMessages(parsed));
  }, []);

  return (
    <>
      <Admonition type="info">
        This documentation is autogenerated from{" "}
        <a href={messagesURL} target="_blank">
          conda-smithy's linter messages JSON document
        </a>
        .
      </Admonition>
      {<MessagesToc toc={toc} messages={messages} />}
      {messages.categories &&
        Object.entries(messages.categories).map(([id, description]) => (
          <div key={`${id}-div`}>
            <Heading as="h2" id={id} key={id}>
              {id}: {description.replaceAll("`", "")}
            </Heading>
            {messages.messages &&
              messages.messages.map(
                (message) =>
                  (message.category == id && (
                    <>
                      <Heading
                        as="h3"
                        id={message.identifier}
                        key={message.identifier}
                      >
                        {(message.deprecated_in && (
                          <s>
                            {message.identifier}: {message.name}
                          </s>
                        )) || (
                          <>
                            {message.identifier}: {message.name}
                          </>
                        )}
                      </Heading>
                      <ul key={`${message.identifier}-ul`}>
                        <li key={`${message.identifier}-kind-${message.kind}`}>
                          {(message.kind == "lint" && "🚨 Lint") || "ℹ️ Hint"}
                        </li>
                        <li
                          key={`${message.identifier}-added-${message.added_in}`}
                        >
                          Added in conda-smithy {message.added_in}
                        </li>
                        {(message.deprecated_in && (
                          <li
                            key={`${message.identifier}-depr-${message.deprecated_in}`}
                          >
                            <strong>
                              Deprecated in {message.deprecated_in}
                            </strong>
                          </li>
                        )) ||
                          null}
                      </ul>
                      <Markdown>{message.documentation}</Markdown>
                      {(message.message.length > 0 && (
                        <>
                          <p>
                            <strong>Message or template</strong>
                          </p>
                          <Admonition type="info" title={null} icon={null}>
                            <Markdown>{message.message}</Markdown>
                          </Admonition>
                        </>
                      )) ||
                        null}
                      {message.examples.length > 0 && (
                        <>
                          <p>
                            <strong>Examples</strong>
                          </p>
                          {message.examples.map((example, idx) => (
                            <Admonition
                              type="note"
                              title={null}
                              icon={null}
                              key={`${message.identifier}-example-${idx}`}
                            >
                              <Markdown>{example}</Markdown>
                            </Admonition>
                          ))}
                        </>
                      )}
                      <hr />
                    </>
                  )) ||
                  null,
              )}
          </div>
        ))}
    </>
  );
}

function MessagesToc({ toc, messages }) {
  <ul>
    {messages.categories &&
      Object.entries(messages.categories).map(([id, desc]) => (
        <li key={id}>
          {toc &&
            toc.push({
              value: `${id}: ${desc.replaceAll("`", "")}`,
              id: id,
              level: 2,
            }) &&
            null}
          <a href={`#${id}`}>{id}</a>
          <ul>
            {messages.messages &&
              messages.messages.map(
                (message) =>
                  message.category == id && (
                    <li key={message.identifier}>
                      {toc &&
                        toc.push({
                          value: message.identifier,
                          id: message.identifier,
                          level: 3,
                        }) &&
                        null}
                      <a href={`#${message.identifier}`}>
                        {message.identifier}
                      </a>
                    </li>
                  ),
              )}
          </ul>
        </li>
      ))}
  </ul>;
}
