blank_issues_enabled: true
contact_links:
  - name: Conda-forge Zulip chatroom
    url: https://conda-forge.zulipchat.com/
    about: Chat to us about conda-forge and ask general questions.
  - name: Conda-forge documentation
    url: https://conda-forge.org/docs/
    about: The complete conda-forge documentation.
  - name: Conda-forge packages
    url: https://conda-forge.org/packages/
    about: For when you have an issue with a specific package.
