#!/usr/bin/env bash

set -ex

# configure bot account
git config --global user.email "pelson.pub+conda-forge@gmail.com"
git config --global user.name "conda-forge-admin"

git checkout -b new_site_content

pushd newsfeed
pip install --no-deps .
popd

python .ci_scripts/generate_html.py

# rebuild elm
# uncomment to restore search
# npm install uglify-js --global
# ./elm-compile.xsh

# build docs into docs/; preserve old README file
mv docs/README docs-README
rm -rf docs/

python .ci_scripts/generate_cfep_index.py

pushd src

# -W --keep-going: list all warnings but fail build in case there are any
# -n: check validity of all links
make html SPHINXOPTS="-W --keep-going -n"
mv _build/html ../docs
rm -rf _build
popd

mv docs-README docs/README
