#!/usr/bin/env bash

set -ex

# configure bot account
if [[ "$CI" == "1" ]]; then
  git config --global user.email "pelson.pub+conda-forge@gmail.com"
  git config --global user.name "conda-forge-admin"
  git checkout -b new_site_content
fi


pushd sphinx/newsfeed
pip install --no-deps .
popd

python .ci_scripts/generate_cfep_index.py

pushd sphinx/src

# -W --keep-going: list all warnings but fail build in case there are any
# -n: check validity of all links
make html SPHINXOPTS="-W --keep-going -n"
linkcheck_failed=0
make linkcheck > /dev/null || linkcheck_failed=1
python ../../.ci_scripts/display_linkcheck.py _build/linkcheck/output.json

if [[ "${GHREF}" != "refs/heads/main" ]]; then
  test "$linkcheck_failed" -eq 0
fi

# Move rendered Sphinx docs to a static directory for Docusaurus to use
rm -rf ../../static-sphinx || true
mkdir -p ../../static-sphinx
mv _build/html ../../static-sphinx/docs
rm -rf _build
popd

# Build docusaurus site
npm install
npm run build
